### ISSUE TITLE
Gather and Post Staff Images

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-wi20#11]
Need an image that each person wants me to use here:

https://courses.cs.washington.edu/courses/cse440/20wi/

- [x] Qisheng
- [x] Jesse
- [x] Richard
- [x] Jena

**Comment by jenamcw** [comment]
![Jena_Photo](https://user-images.githubusercontent.com/58831546/71325587-d29d1300-24a3-11ea-9d38-06067a97acdb.jpg)

**Comment by QishengLi** [comment]
![qisheng_photo](https://user-images.githubusercontent.com/10660578/71553223-40739e00-29c0-11ea-82f4-82efa3d240e1.jpg)

Should we also add the photos to the repo directly by making a pull request?

**Comment by jayfo** [comment]
@lichard49 and @jessjmart : Still need these

**Comment by jessjmart** [comment]
![JesseMartinezHeadshot](https://user-images.githubusercontent.com/37155840/71699189-44fad680-2d73-11ea-859d-2412f269d219.jpg)

**Comment by lichard49** [comment]
Sigh meant to find time and take a new go-to picture...
![me](https://user-images.githubusercontent.com/2752015/71721711-f41ec880-2dda-11ea-9d09-18f8337bca12.jpg)

**Comment by jayfo** [comment]
Hooray that's all of them!
