### ISSUE TITLE
Schedule Office Hours

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-wi20#12]
I'd like Qisheng and Jesse to schedule an office hour. It's generally worked well to have one on Wednesday and one on Thursday, as this gives students room to follow up with you between any Tuesday milestone, any feedback we send them, and their Thursday night milestone.

Note that I have a policy that office hours require an email from the students 1 hour beforehand, or they risk that you may not be there. No reason to sit in an empty room for an hour.

- [x] Pick day/time preferences
- [x] Reserve rooms
- [ ] Add to syllabus
- [ ] Add to course calendar

**Comment by jayfo** [comment]
@QishengLi and @jessjmart : The longer we wait to schedule this, the harder it'll be to find a room.

**Comment by jessjmart** [comment]
Wed/Thurs sounds good to me— I’m pretty open both days (more so in the afternoons) and don’t have particularly strong preferences as to day/time. 

Assuming there are rooms available, my ideal times would be **2-3pm on Wednesday or Thursday**.

@jayfo, how can I check room availability?

**Comment by QishengLi** [comment]
I would prefer a time slot on Wednesday morning if that works for you, @jessjmart . I just made the reservation at Allen Center 4th-floor breakout area at **10 - 11 on Weds**.

@jessjmart : you can check room availabilities & make reservations here: https://reserve.cs.washington.edu/room/day.php. Let me know if you need help!

**Comment by jessjmart** [comment]
Ok nice, I reserved the same room for 2-3 on Thursday

@jayfo, looks like we’re all set to add the OH to the syllabus & calendar!

**Comment by jayfo** [comment]
@jessjmart : Your reservation was accidentally from 1pm to 2pm. I moved it to 2pm to 3pm.

Assuming that was the bug, this was the correct time.

**Comment by jayfo** [comment]
@QishengLi and @jessjmart : I've now posted these on the website and calendar:

https://courses.cs.washington.edu/courses/cse440/20wi/

https://courses.cs.washington.edu/courses/cse440/20wi/calendar

Can you confirm I got them right?

Note that I did not start your office hours until week 3, as there's no need.

We'll also preemptively cancel a few of these as we finalize other things.

**Comment by QishengLi** [comment]
Yes, these are correct for me!

**Comment by jessjmart** [comment]
Yes that was a mistake, thanks for the fix, @jayfo ! Mine are correct as well.
