### ISSUE TITLE
Confirm 2/26 for Exam Grading

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-wi20#25]
I just sent a calendar invite for us to spend the day grading on 2/26.

Since we'll have the exam on 2/25, I prefer to just sit in a room for a day and get this done. We can work around a certain amount of "come and go" when people have inflexible commitments (e.g., class). But I'm going to cancel/skip most other things that day.

If too many, another option might be to start on 2/25, finish in the morning on 2/26. But the "all at once" approach has generally been easier/better, even if it's a bit intimidating on your calendar.

What firm constraints do people have on 2/26?

**Comment by jessjmart** [comment]
Currently I've just got class from 10-11:20; outside of that, I should be free to grade 👍

**Comment by jenamcw** [comment]
I have class on Wednesdays from 1:30 - 2:30 and 2:30-5:30, but I could try and find some wiggle room once I see the class plans for the 26th.

**Comment by lichard49** [comment]
I tentatively also have class from 10-11:20 on Wednesdays, but I generally have no qualms prioritizing things that need to get done!

**Comment by QishengLi** [comment]
I should be available all day if there is no required meeting on 2/26.

**Comment by jayfo** [comment]
Ok this will work.  I'll plan to grade "all day", and people will come and go as required. We'll get some food.

Will coordinate in more detail when we get closer.
