### ISSUE TITLE
Get Planned Away Dates on Calendar

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-wi20#32]
As part of our organization and transparency with the students, I'd like the course calendar to include any days that we know we'll be away from class. Right now, that's only Jena on Jan 7:

https://courses.cs.washington.edu/courses/cse440/20wi/calendar

Let me know any dates that people will need to be away. We'll post them, and we'll come up with a plan to cover them.

Of course, "waking up with the flu" is unpredictable and we'll scramble that day if it happens.

**Comment by jayfo** [comment]
Also, if you don't have any other planned away dates, can you comment that so I know we're resolved?

**Comment by jenamcw** [comment]
I do not have any other planned away dates.

**Comment by jessjmart** [comment]
I might be out of town 2/8-2/10, but not sure yet-- should know for sure later tonight/tomorrow. Other than that, should be around all quarter

**Comment by QishengLi** [comment]
I also don’t have any planned trip for the quarter as of now.

Best,
Qisheng

**Comment by lichard49** [comment]
I don't have any travel plans right now but I like to think that my life is exciting enough something might pop up (read: not likely)

**Comment by jayfo** [comment]
@jessjmart : Did your potential way resolve?

**Comment by jessjmart** [comment]
yes, I'll be out of town 2/8 to 2/10 but that should be my only away!

**Comment by jayfo** [comment]
Ok I've calendared Jesse as away 2/10, will close this out.

Let me know if any other planned away comes up!
